---
- name: install supervisor
  yum: name=supervisor
  tags: supervisor

- name: configure supervisord
  shell: /usr/bin/echo_supervisord_conf > {{supervisor.config.file}}
  tags: supervisor

- name: backup default configuration
  shell: cp {{supervisor.config.file}} {{supervisor.config.default}} creates={{supervisor.config.default}}
  tags: supervisor

- name: prepare necessary directories
  file: path={{item}} state=directory recurse=yes
  with_items:
    - "{{supervisor.log.dir}}"
    - "{{supervisor.config.dir}}"
    - "{{supervisor.runtime.dir}}"
  tags: supervisor

- name: copy config file
  template:
    src: templates/server.ini
    dest: /etc/supervisord.d/server.ini
    owner: root
    group: root
    mode: '0644'

- name: tell supervisor to include relative configurations directory
  ini_file: dest={{supervisor.config.file}}
            section=include
            option=files
            value={{supervisor.config.dir}}/*.ini
            state=present
  tags: supervisor

- name: make sure supervisord is running and up-to-date
  shell: echo Magic...
  notify:
    - restart supervisord
    #- run supervisord
    - reread supervisord config
  tags:
    - run-supervisord  
    - supervisor
