- name: Check that deploy.php exist
  stat:
    path: /var/www/html/deploy.php
  register: stat_result

- name: Install deployer step one
  get_url: url=https://deployer.org/deployer.phar  dest=/tmp mode=755
  when: not stat_result.stat.exists

- name: Install deployer step two
  shell: |
    mv /tmp/deployer.phar /usr/bin/dep
    chown root:root /usr/bin/dep
    chmod +x /usr/bin/dep
  when: not stat_result.stat.exists


- name: Copy deploy.php
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'templates/deploy.php', dest: '/var/www/html/__deploy.php' }
    - { src: 'templates/setup.php', dest: '/var/www/html/deploy.php' }
  when: not stat_result.stat.exists