---
- name: restart supervisord
  service: name=supervisord state=restarted enabled=yes

- name: run supervisord
  shell: /usr/bin/supervisord -c {{supervisor.config.file}} creates="{{supervisor.runtime.dir}}/{{supervisor.runtime.socket}}"

- name: reread supervisord config
  shell: /usr/bin/supervisorctl reread
